import { MigrationInterface, QueryRunner } from "typeorm";

export class ActualizacionEntidades1787524208767 implements MigrationInterface {
    name = 'ActualizacionEntidades1787524208767'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "vendedor_zona" DROP CONSTRAINT "vendedor_zona_vendedor_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "vendedor_zona" DROP CONSTRAINT "vendedor_zona_zona_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "reasignaciones" DROP CONSTRAINT "reasignaciones_lead_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "reasignaciones" DROP CONSTRAINT "reasignaciones_vendedor_anterior_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "reasignaciones" DROP CONSTRAINT "reasignaciones_vendedor_nuevo_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "mensajes" DROP CONSTRAINT "mensajes_conversacion_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "conversaciones" DROP CONSTRAINT "conversaciones_lead_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "conversaciones" DROP CONSTRAINT "conversaciones_vendedor_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "leads" DROP CONSTRAINT "leads_zona_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "leads" DROP CONSTRAINT "leads_vendedor_asignado_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "leads" DROP CONSTRAINT "leads_cliente_id_fkey"`);
        await queryRunner.query(`DROP INDEX "public"."idx_vendedor_zona_vendedor_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_vendedor_zona_zona_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_clientes_vendedor_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_clientes_estado"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tickets_vendedor_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_actividades_cliente_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_actividades_vendedor_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_reuniones_vendedor_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_oportunidades_vendedor_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_pedidos_vendedor_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_metas_vendedor_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notificaciones_vendedor_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_reasignaciones_lead_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_reasignaciones_vendedor_anterior_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_reasignaciones_vendedor_nuevo_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_reasignaciones_motivo"`);
        await queryRunner.query(`DROP INDEX "public"."idx_reasignaciones_fecha"`);
        await queryRunner.query(`DROP INDEX "public"."idx_mensajes_conversacion_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_mensajes_remitente_tipo"`);
        await queryRunner.query(`DROP INDEX "public"."idx_mensajes_fecha_creacion"`);
        await queryRunner.query(`DROP INDEX "public"."idx_conversaciones_vendedor_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_conversaciones_estado"`);
        await queryRunner.query(`DROP INDEX "public"."idx_conversaciones_ultimo_mensaje_en"`);
        await queryRunner.query(`DROP INDEX "public"."idx_leads_vendedor_asignado_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_leads_zona_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_leads_estado"`);
        await queryRunner.query(`DROP INDEX "public"."idx_leads_origen"`);
        await queryRunner.query(`DROP INDEX "public"."idx_leads_fecha_creacion"`);
        await queryRunner.query(`ALTER TABLE "vendedor_zona" DROP CONSTRAINT "uq_vendedor_zona"`);
        await queryRunner.query(`ALTER TABLE "productos_pedido" ADD "precio_base" numeric(12,4) NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "productos_pedido" ADD "porcentaje_negociacion" numeric(12,4) NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "clientes" ALTER COLUMN "fecha_creacion" SET DEFAULT '"2026-08-23T22:30:16.594Z"'`);
        await queryRunner.query(`ALTER TABLE "clientes" ALTER COLUMN "fecha_actualizacion" SET DEFAULT '"2026-08-23T22:30:16.594Z"'`);
        await queryRunner.query(`ALTER TABLE "menu_bienvenida" ALTER COLUMN "opciones_intencion" SET DEFAULT '[{"numero":1,"etiqueta":"Cotización","tipo_web":"cotizacion"},{"numero":2,"etiqueta":"Información","tipo_web":"informacion"},{"numero":3,"etiqueta":"Soporte","tipo_web":"soporte"}]'`);
        await queryRunner.query(`CREATE INDEX "IDX_034dd9bb7a46df6d4c77e0b2d2" ON "vendedor_zona" ("zona_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bec16e7acc0c00c26700d375b0" ON "vendedor_zona" ("vendedor_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_42eef3829fe6d1c1b0e27778f7" ON "reasignaciones" ("fecha") `);
        await queryRunner.query(`CREATE INDEX "IDX_062d39bfdefed11b470d99b0ee" ON "reasignaciones" ("motivo") `);
        await queryRunner.query(`CREATE INDEX "IDX_44d1e7185568f2e92b1da5ebfd" ON "reasignaciones" ("vendedor_nuevo_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8eb640876790b2abe7bc6c7bf3" ON "reasignaciones" ("vendedor_anterior_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_6088bccede9d14c13d06bb5812" ON "reasignaciones" ("lead_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_0c6dd0f734cf96140048099cd8" ON "mensajes" ("fecha_creacion") `);
        await queryRunner.query(`CREATE INDEX "IDX_9842cae63259de4c293afa5e64" ON "mensajes" ("remitente_tipo") `);
        await queryRunner.query(`CREATE INDEX "IDX_7f8b407efa1135b971fdd05c07" ON "mensajes" ("conversacion_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7ac0d03cb2185c8bfe06d9f6c0" ON "conversaciones" ("ultimo_mensaje_en") `);
        await queryRunner.query(`CREATE INDEX "IDX_a6eb19dacc9f5f2c7b916c6227" ON "conversaciones" ("estado") `);
        await queryRunner.query(`CREATE INDEX "IDX_8cf2b1abb78f953a04935a4996" ON "conversaciones" ("vendedor_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e0a671137d75b46520dfcb8797" ON "leads" ("fecha_creacion") `);
        await queryRunner.query(`CREATE INDEX "IDX_6e97e05e19f2fb9e3c3186c292" ON "leads" ("origen") `);
        await queryRunner.query(`CREATE INDEX "IDX_0e991b4928c09964472e68f6f9" ON "leads" ("estado") `);
        await queryRunner.query(`CREATE INDEX "IDX_6cd614ca489dc09cfbc3a383be" ON "leads" ("zona_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a3147e74319e032452b68a791f" ON "leads" ("vendedor_asignado_id") `);
        await queryRunner.query(`ALTER TABLE "vendedor_zona" ADD CONSTRAINT "UQ_5379b20a37dfbe375ccba18b4e2" UNIQUE ("vendedor_id", "zona_id")`);
        await queryRunner.query(`ALTER TABLE "vendedor_zona" ADD CONSTRAINT "FK_bec16e7acc0c00c26700d375b08" FOREIGN KEY ("vendedor_id") REFERENCES "vendedores"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vendedor_zona" ADD CONSTRAINT "FK_034dd9bb7a46df6d4c77e0b2d29" FOREIGN KEY ("zona_id") REFERENCES "zonas"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reasignaciones" ADD CONSTRAINT "FK_6088bccede9d14c13d06bb5812e" FOREIGN KEY ("lead_id") REFERENCES "leads"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reasignaciones" ADD CONSTRAINT "FK_8eb640876790b2abe7bc6c7bf38" FOREIGN KEY ("vendedor_anterior_id") REFERENCES "vendedores"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reasignaciones" ADD CONSTRAINT "FK_44d1e7185568f2e92b1da5ebfd8" FOREIGN KEY ("vendedor_nuevo_id") REFERENCES "vendedores"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mensajes" ADD CONSTRAINT "FK_7f8b407efa1135b971fdd05c079" FOREIGN KEY ("conversacion_id") REFERENCES "conversaciones"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversaciones" ADD CONSTRAINT "FK_90aeb9b13c137e30a7e03b82483" FOREIGN KEY ("lead_id") REFERENCES "leads"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversaciones" ADD CONSTRAINT "FK_8cf2b1abb78f953a04935a49964" FOREIGN KEY ("vendedor_id") REFERENCES "vendedores"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leads" ADD CONSTRAINT "FK_a3147e74319e032452b68a791fe" FOREIGN KEY ("vendedor_asignado_id") REFERENCES "vendedores"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leads" ADD CONSTRAINT "FK_7a2141de6b4909386c64e582ab2" FOREIGN KEY ("cliente_id") REFERENCES "clientes"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leads" ADD CONSTRAINT "FK_6cd614ca489dc09cfbc3a383beb" FOREIGN KEY ("zona_id") REFERENCES "zonas"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "leads" DROP CONSTRAINT "FK_6cd614ca489dc09cfbc3a383beb"`);
        await queryRunner.query(`ALTER TABLE "leads" DROP CONSTRAINT "FK_7a2141de6b4909386c64e582ab2"`);
        await queryRunner.query(`ALTER TABLE "leads" DROP CONSTRAINT "FK_a3147e74319e032452b68a791fe"`);
        await queryRunner.query(`ALTER TABLE "conversaciones" DROP CONSTRAINT "FK_8cf2b1abb78f953a04935a49964"`);
        await queryRunner.query(`ALTER TABLE "conversaciones" DROP CONSTRAINT "FK_90aeb9b13c137e30a7e03b82483"`);
        await queryRunner.query(`ALTER TABLE "mensajes" DROP CONSTRAINT "FK_7f8b407efa1135b971fdd05c079"`);
        await queryRunner.query(`ALTER TABLE "reasignaciones" DROP CONSTRAINT "FK_44d1e7185568f2e92b1da5ebfd8"`);
        await queryRunner.query(`ALTER TABLE "reasignaciones" DROP CONSTRAINT "FK_8eb640876790b2abe7bc6c7bf38"`);
        await queryRunner.query(`ALTER TABLE "reasignaciones" DROP CONSTRAINT "FK_6088bccede9d14c13d06bb5812e"`);
        await queryRunner.query(`ALTER TABLE "vendedor_zona" DROP CONSTRAINT "FK_034dd9bb7a46df6d4c77e0b2d29"`);
        await queryRunner.query(`ALTER TABLE "vendedor_zona" DROP CONSTRAINT "FK_bec16e7acc0c00c26700d375b08"`);
        await queryRunner.query(`ALTER TABLE "vendedor_zona" DROP CONSTRAINT "UQ_5379b20a37dfbe375ccba18b4e2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a3147e74319e032452b68a791f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6cd614ca489dc09cfbc3a383be"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0e991b4928c09964472e68f6f9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6e97e05e19f2fb9e3c3186c292"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e0a671137d75b46520dfcb8797"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8cf2b1abb78f953a04935a4996"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a6eb19dacc9f5f2c7b916c6227"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7ac0d03cb2185c8bfe06d9f6c0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7f8b407efa1135b971fdd05c07"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9842cae63259de4c293afa5e64"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0c6dd0f734cf96140048099cd8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6088bccede9d14c13d06bb5812"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8eb640876790b2abe7bc6c7bf3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_44d1e7185568f2e92b1da5ebfd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_062d39bfdefed11b470d99b0ee"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_42eef3829fe6d1c1b0e27778f7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bec16e7acc0c00c26700d375b0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_034dd9bb7a46df6d4c77e0b2d2"`);
        await queryRunner.query(`ALTER TABLE "menu_bienvenida" ALTER COLUMN "opciones_intencion" SET DEFAULT '[{"numero": 1, "etiqueta": "Cotización", "tipo_web": "cotizacion"}, {"numero": 2, "etiqueta": "Información", "tipo_web": "informacion"}, {"numero": 3, "etiqueta": "Soporte", "tipo_web": "soporte"}]'`);
        await queryRunner.query(`ALTER TABLE "clientes" ALTER COLUMN "fecha_actualizacion" SET DEFAULT '2026-08-19'`);
        await queryRunner.query(`ALTER TABLE "clientes" ALTER COLUMN "fecha_creacion" SET DEFAULT '2026-08-19'`);
        await queryRunner.query(`ALTER TABLE "productos_pedido" DROP COLUMN "porcentaje_negociacion"`);
        await queryRunner.query(`ALTER TABLE "productos_pedido" DROP COLUMN "precio_base"`);
        await queryRunner.query(`ALTER TABLE "vendedor_zona" ADD CONSTRAINT "uq_vendedor_zona" UNIQUE ("vendedor_id", "zona_id")`);
        await queryRunner.query(`CREATE INDEX "idx_leads_fecha_creacion" ON "leads" ("fecha_creacion") `);
        await queryRunner.query(`CREATE INDEX "idx_leads_origen" ON "leads" ("origen") `);
        await queryRunner.query(`CREATE INDEX "idx_leads_estado" ON "leads" ("estado") `);
        await queryRunner.query(`CREATE INDEX "idx_leads_zona_id" ON "leads" ("zona_id") `);
        await queryRunner.query(`CREATE INDEX "idx_leads_vendedor_asignado_id" ON "leads" ("vendedor_asignado_id") `);
        await queryRunner.query(`CREATE INDEX "idx_conversaciones_ultimo_mensaje_en" ON "conversaciones" ("ultimo_mensaje_en") `);
        await queryRunner.query(`CREATE INDEX "idx_conversaciones_estado" ON "conversaciones" ("estado") `);
        await queryRunner.query(`CREATE INDEX "idx_conversaciones_vendedor_id" ON "conversaciones" ("vendedor_id") `);
        await queryRunner.query(`CREATE INDEX "idx_mensajes_fecha_creacion" ON "mensajes" ("fecha_creacion") `);
        await queryRunner.query(`CREATE INDEX "idx_mensajes_remitente_tipo" ON "mensajes" ("remitente_tipo") `);
        await queryRunner.query(`CREATE INDEX "idx_mensajes_conversacion_id" ON "mensajes" ("conversacion_id") `);
        await queryRunner.query(`CREATE INDEX "idx_reasignaciones_fecha" ON "reasignaciones" ("fecha") `);
        await queryRunner.query(`CREATE INDEX "idx_reasignaciones_motivo" ON "reasignaciones" ("motivo") `);
        await queryRunner.query(`CREATE INDEX "idx_reasignaciones_vendedor_nuevo_id" ON "reasignaciones" ("vendedor_nuevo_id") `);
        await queryRunner.query(`CREATE INDEX "idx_reasignaciones_vendedor_anterior_id" ON "reasignaciones" ("vendedor_anterior_id") `);
        await queryRunner.query(`CREATE INDEX "idx_reasignaciones_lead_id" ON "reasignaciones" ("lead_id") `);
        await queryRunner.query(`CREATE INDEX "idx_notificaciones_vendedor_id" ON "notificaciones" ("vendedor_id") `);
        await queryRunner.query(`CREATE INDEX "idx_metas_vendedor_id" ON "metas" ("vendedor_id") `);
        await queryRunner.query(`CREATE INDEX "idx_pedidos_vendedor_id" ON "pedidos" ("vendedor_id") `);
        await queryRunner.query(`CREATE INDEX "idx_oportunidades_vendedor_id" ON "oportunidades" ("vendedor_id") `);
        await queryRunner.query(`CREATE INDEX "idx_reuniones_vendedor_id" ON "reuniones" ("vendedor_id") `);
        await queryRunner.query(`CREATE INDEX "idx_actividades_vendedor_id" ON "actividades" ("vendedor_id") `);
        await queryRunner.query(`CREATE INDEX "idx_actividades_cliente_id" ON "actividades" ("cliente_id") `);
        await queryRunner.query(`CREATE INDEX "idx_tickets_vendedor_id" ON "tickets" ("vendedor_id") `);
        await queryRunner.query(`CREATE INDEX "idx_clientes_estado" ON "clientes" ("estado") `);
        await queryRunner.query(`CREATE INDEX "idx_clientes_vendedor_id" ON "clientes" ("vendedor_id") `);
        await queryRunner.query(`CREATE INDEX "idx_vendedor_zona_zona_id" ON "vendedor_zona" ("zona_id") `);
        await queryRunner.query(`CREATE INDEX "idx_vendedor_zona_vendedor_id" ON "vendedor_zona" ("vendedor_id") `);
        await queryRunner.query(`ALTER TABLE "leads" ADD CONSTRAINT "leads_cliente_id_fkey" FOREIGN KEY ("cliente_id") REFERENCES "clientes"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leads" ADD CONSTRAINT "leads_vendedor_asignado_id_fkey" FOREIGN KEY ("vendedor_asignado_id") REFERENCES "vendedores"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leads" ADD CONSTRAINT "leads_zona_id_fkey" FOREIGN KEY ("zona_id") REFERENCES "zonas"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversaciones" ADD CONSTRAINT "conversaciones_vendedor_id_fkey" FOREIGN KEY ("vendedor_id") REFERENCES "vendedores"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversaciones" ADD CONSTRAINT "conversaciones_lead_id_fkey" FOREIGN KEY ("lead_id") REFERENCES "leads"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mensajes" ADD CONSTRAINT "mensajes_conversacion_id_fkey" FOREIGN KEY ("conversacion_id") REFERENCES "conversaciones"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reasignaciones" ADD CONSTRAINT "reasignaciones_vendedor_nuevo_id_fkey" FOREIGN KEY ("vendedor_nuevo_id") REFERENCES "vendedores"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reasignaciones" ADD CONSTRAINT "reasignaciones_vendedor_anterior_id_fkey" FOREIGN KEY ("vendedor_anterior_id") REFERENCES "vendedores"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reasignaciones" ADD CONSTRAINT "reasignaciones_lead_id_fkey" FOREIGN KEY ("lead_id") REFERENCES "leads"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vendedor_zona" ADD CONSTRAINT "vendedor_zona_zona_id_fkey" FOREIGN KEY ("zona_id") REFERENCES "zonas"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vendedor_zona" ADD CONSTRAINT "vendedor_zona_vendedor_id_fkey" FOREIGN KEY ("vendedor_id") REFERENCES "vendedores"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
